FROM python:3.9.5-slim

RUN apt-get update && apt-get install -y cron

RUN pip install --no-cache-dir requests

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

RUN echo "*/15 * * * * /usr/local/bin/python /app/getControllerApplications.py DEBUG /app/database.ini >> /app/concon_log.log 2>&1" > /etc/cron.d/concon_cron

RUN chmod 0644 /etc/cron.d/concon_cron

RUN /usr/bin/crontab /etc/cron.d/concon_cron

CMD ["cron", "-f"]
